package visual;


import exception.InitException;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import exception.WindowException;
import javax.swing.ImageIcon;


public class App extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public App() {
        initComponents();
        
        /* Gerenciando o visual */
        this.getContentPane().setBackground(new java.awt.Color(255, 254, 240));        
        
        /* Adicionando Ícone à janela */
        try {
            URL caminhoImagem = this.getClass().getClassLoader().getResource("favicon.png");
            Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
            setIconImage(iconeTitulo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar o ícone \"favicon.png\".");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTeste = new javax.swing.JLabel();
        lblDialogo = new javax.swing.JLabel();
        cmbBoxDataset = new javax.swing.JComboBox<>();
        btnParar = new javax.swing.JButton();
        btnEscolher = new javax.swing.JButton();
        btnProximaEpoca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuTreinamento = new javax.swing.JMenu();
        subMenuIniciar = new javax.swing.JMenuItem();
        subMenuParar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subMenuSair = new javax.swing.JMenuItem();
        menuDataset = new javax.swing.JMenu();
        subMenuCriarDataset = new javax.swing.JMenuItem();
        subMenuDeletarDataset = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        subMenuComoUsar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perceptron - Reconhecimento de Figuras");
        setMinimumSize(new java.awt.Dimension(960, 720));
        setPreferredSize(new java.awt.Dimension(960, 720));
        setResizable(false);

        lblTeste.setText("  Círculo Vermelho");

        lblDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balaoDialogoPadrao.png"))); // NOI18N

        cmbBoxDataset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbBoxDataset.setEnabled(false);

        btnParar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnParar.setText("Parar");
        btnParar.setEnabled(false);
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        btnEscolher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEscolher.setText("Escolher");
        btnEscolher.setEnabled(false);
        btnEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherActionPerformed(evt);
            }
        });

        btnProximaEpoca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProximaEpoca.setText("Próxima Época");
        btnProximaEpoca.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATASET:");

        menuTreinamento.setText("Treinamento");
        menuTreinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTreinamentoActionPerformed(evt);
            }
        });

        subMenuIniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        subMenuIniciar.setText("Iniciar Rede");
        subMenuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuIniciarActionPerformed(evt);
            }
        });
        menuTreinamento.add(subMenuIniciar);

        subMenuParar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        subMenuParar.setText("Parar Rede");
        subMenuParar.setEnabled(false);
        subMenuParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPararActionPerformed(evt);
            }
        });
        menuTreinamento.add(subMenuParar);
        menuTreinamento.add(jSeparator2);

        subMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        subMenuSair.setText("Sair");
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuTreinamento.add(subMenuSair);

        barraMenu.add(menuTreinamento);

        menuDataset.setText("Dataset");
        menuDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDatasetActionPerformed(evt);
            }
        });

        subMenuCriarDataset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        subMenuCriarDataset.setText("Criar Dataset");
        subMenuCriarDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCriarDatasetActionPerformed(evt);
            }
        });
        menuDataset.add(subMenuCriarDataset);

        subMenuDeletarDataset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        subMenuDeletarDataset.setText("Excluir Dataset");
        subMenuDeletarDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDeletarDatasetActionPerformed(evt);
            }
        });
        menuDataset.add(subMenuDeletarDataset);

        barraMenu.add(menuDataset);

        menuAjuda.setText("Ajuda");

        subMenuComoUsar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        subMenuComoUsar.setText("Como Utilizar");
        subMenuComoUsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuComoUsarActionPerformed(evt);
            }
        });
        menuAjuda.add(subMenuComoUsar);
        menuAjuda.add(jSeparator1);

        subMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        subMenuSobre.setText("Sobre");
        subMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(subMenuSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(cmbBoxDataset, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnProximaEpoca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblTeste)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblDialogo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxDataset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximaEpoca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(106, 106, 106)
                .addComponent(lblTeste)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSobreActionPerformed
        JOptionPane.showMessageDialog(null, "\nRede Neural Perceptron para reconhecimento de figuras a\npartir de um dataset textual.\n\n" 
                                            + "Projeto desenvolvido para a disciplina Inteligência Artificial I        \n"
                                            + "Curso: Ciências da Computação (UNISANTOS)\n"
                                            + "Professor: Márcio Piva\n\n"  
                                            + "Desenvolvedores:\n\nRodrigo Pontes\nLuana Quelhas\nDiego Assis\nHiero Bartholo\n\n"
                                            + "Versão 2.0\n(04/2018)");
    }//GEN-LAST:event_subMenuSobreActionPerformed

    private void subMenuComoUsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuComoUsarActionPerformed
        JOptionPane.showMessageDialog(null, "\n               ESCOLHA UM DATASET\n\n"
                                             + "+ Escolha um dataset pré-definido, ou\n+ Crie o seu próprio dataset\n\n"
                                             + "               INICIE O TREINAMENTO\n\n"
                                             + "+ Escolha entre pular para o resultado final, ou  \n+ Assista o treinamento a cada iteração\n\n");
                                             
    }//GEN-LAST:event_subMenuComoUsarActionPerformed

    private void subMenuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuIniciarActionPerformed
        menuDataset.setEnabled(false);
        
        subMenuIniciar.setEnabled(false);
        subMenuParar.setEnabled(true);
        subMenuCriarDataset.setEnabled(false);
        subMenuDeletarDataset.setEnabled(false);
        
        cmbBoxDataset.setEnabled(true);        
        adicionarDatasetsNaComboBox();
        
        btnParar.setEnabled(true);
        btnEscolher.setEnabled(true);
        
        mudaBalaoDialogo("balaoDialogoEscolha.png");
    }//GEN-LAST:event_subMenuIniciarActionPerformed

    private void subMenuCriarDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCriarDatasetActionPerformed
        FormCriarDataset formDataset = new FormCriarDataset(this, true);
    }//GEN-LAST:event_subMenuCriarDatasetActionPerformed

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_subMenuSairActionPerformed

    private void subMenuDeletarDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDeletarDatasetActionPerformed
        try {
            DeletarDataset formDeletar = new DeletarDataset(this, true);
        } catch (WindowException ex) {
            JOptionPane.showMessageDialog(null, "Não há nenhum dataset personalizado para excluir!");
        }
    }//GEN-LAST:event_subMenuDeletarDatasetActionPerformed

    private void menuTreinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTreinamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTreinamentoActionPerformed

    private void subMenuPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPararActionPerformed
        menuDataset.setEnabled(true);
        
        subMenuIniciar.setEnabled(true);
        subMenuParar.setEnabled(false);
        subMenuCriarDataset.setEnabled(true);
        subMenuDeletarDataset.setEnabled(true);
        
        cmbBoxDataset.removeAllItems();
        cmbBoxDataset.setEnabled(false);
        
        btnEscolher.setEnabled(false);
        btnParar.setEnabled(false);
        btnProximaEpoca.setEnabled(false);        
        
        mudaBalaoDialogo("balaoDialogoPadrao.png");
    }//GEN-LAST:event_subMenuPararActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        subMenuPararActionPerformed(evt);
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherActionPerformed
        File dataset = new File(".\\src\\dataset\\" + cmbBoxDataset.getSelectedItem().toString());
        
        cmbBoxDataset.setEnabled(false);
        
        btnEscolher.setEnabled(false);
        btnProximaEpoca.setEnabled(true);
        
        mudaBalaoDialogo("balaoDialogoIniciarTreinamento.png");
        
        
        
        /*try {
            //Carrega as imagens
            BufferedImage image = ImageIO.read(new File(".\\src\\imagens\\corVermelho.png"));
            BufferedImage image2 = ImageIO.read(new File(".\\src\\imagens\\formaCirculo.png"));
            int w = image2.getWidth();
            int h = image2.getHeight();
            //Obtém o Graphics2D da imagem 1 (fundo), para desenhar sobre ela o logo.
            Graphics2D graphics = image.createGraphics();
            graphics.drawImage(image2, 0, 0, w, h, null);
            graphics.dispose(); //Libera os recursos ocupados pela "Caneta"
            //Use esse ImageIcon para desenhar no seu form
            ImageIcon icon = new ImageIcon(image);
            //icon.paintIcon(lblTeste, graphics, 50, 50);
            lblTeste.setIcon(icon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar as imagens do projeto.\n\n"
                    + "Baixe o projeto completo e funcional na íntegra em:\n"
                    + "https://github.com/rodrigopontezz/RedeNeuralFiguras\n");
        }*/
    }//GEN-LAST:event_btnEscolherActionPerformed

    private void menuDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDatasetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDatasetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            verificaArquivosNecessarios();
            
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    App form = new App();
                    form.setLocationRelativeTo(null);
                    form.setVisible(true);
                }
            });
        } catch (IOException | InitException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()
                    + "\n\nBaixe o projeto funcional na íntegra em:\n"
                    + "https://github.com/rodrigopontezz/RedeNeuralFiguras\n");
        }
    }
    
    public static void verificaArquivosNecessarios() throws IOException, InitException {
        File file = new File(".\\src\\dataset");
        if (!file.exists())  throw new InitException("Diretório src/dataset não encontrado.");
        
        file = new File(".\\src\\imagens");
        if (!file.exists())  throw new InitException("Diretório src/imagens não encontrado.");
        
        int check = 0;
        
        for (File fileEntry : file.listFiles()) {
            if (fileEntry.getName().equals("balaoDialogoEscolha.png") ||
                    fileEntry.getName().equals("balaoDialogoIniciarTreinamento.png") ||
                    fileEntry.getName().equals("balaoDialogoNeuroniosAcertaram.png") ||
                    fileEntry.getName().equals("balaoDialogoNeuroniosErraram.png") ||
                    fileEntry.getName().equals("balaoDialogoPadrao.png") ||
                    fileEntry.getName().equals("corAmarelo.png") ||
                    fileEntry.getName().equals("corAzul.png") ||
                    fileEntry.getName().equals("corPreto.png") ||
                    fileEntry.getName().equals("corRosa.png") ||
                    fileEntry.getName().equals("corVerde.png") ||
                    fileEntry.getName().equals("corVermelho.png") ||
                    fileEntry.getName().equals("formaCirculo.png") ||
                    fileEntry.getName().equals("formaCoracao.png") ||
                    fileEntry.getName().equals("formaEstrela.png") ||
                    fileEntry.getName().equals("formaQuadrado.png") ||
                    fileEntry.getName().equals("formaTrapezio.png") ||
                    fileEntry.getName().equals("formaTriangulo.png")) check++;
        }
        
        if (check != 17) throw new InitException("Diretório src/imagens está corrompido.");
        
        file = new File(".\\src\\dataset\\figuras.txt");
        
        PrintWriter pw = new PrintWriter(new FileWriter(file));
        
        pw.println("Triângulo Amarelo");
        pw.println("Círculo Azul");
        pw.println("Estrela Amarelo");
        pw.println("Coração Vermelho");
        pw.println("Trapézio Preto");
        pw.println("Triângulo Rosa");
        pw.println("Círculo Vermelho");
        pw.print("Quadrado Verde");
        pw.close();
    }
    
    public void adicionarDatasetsNaComboBox() {
        File folder = new File(".\\src\\dataset");
        
        if (folder.listFiles().length <  3) {
            JOptionPane.showMessageDialog(null, "Não foi possível acessar os arquivos de dataset.\n\n"
                    + "Baixe o projeto funcional na íntegra em:\n"
                    + "https://github.com/rodrigopontezz/RedeNeuralFiguras\n");
            throw new WindowException();
        } else {
            for (final File fileEntry : folder.listFiles()) {
                if (fileEntry.isFile()) {
                    String nomeDataset = fileEntry.getName();
                    
                    if (!nomeDataset.equals("formas.txt") && !nomeDataset.equals("cores.txt")) {
                        cmbBoxDataset.addItem(nomeDataset);
                    }
                }
            }
        }
    }
    
    public void mudaBalaoDialogo(String nomeImagem) {
        ImageIcon icon = new ImageIcon(".\\src\\imagens\\" + nomeImagem);
        lblDialogo.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnEscolher;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnProximaEpoca;
    private javax.swing.JComboBox<String> cmbBoxDataset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblDialogo;
    private javax.swing.JLabel lblTeste;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuDataset;
    private javax.swing.JMenu menuTreinamento;
    private javax.swing.JMenuItem subMenuComoUsar;
    private javax.swing.JMenuItem subMenuCriarDataset;
    private javax.swing.JMenuItem subMenuDeletarDataset;
    private javax.swing.JMenuItem subMenuIniciar;
    private javax.swing.JMenuItem subMenuParar;
    private javax.swing.JMenuItem subMenuSair;
    private javax.swing.JMenuItem subMenuSobre;
    // End of variables declaration//GEN-END:variables
}
